config/routes.rb
Rails.application.routes.draw do
  root to: "top#index"
  get "about_us" => "top#about_us"
  get "show_item" => "top#show_item"
  get "categorized" => "top#categorized"  
  get "get_image1" => "top#get_image1"
  get "get_image2" => "top#get_image2"
  get "get_image3" => "top#get_image3"
  get "get_image4" => "top#get_image4"
  get "new_arrivals" => "top#new_arrivals"
  get "recommend" => "top#recommend"
  get "blog" => "top#blog"
  get "contact" => "top#contact"
  get "search" => "top#search"
  get "checkout" => "top#checkout"
  get "delete_cart_item" => "top#delete_cart_item"
  get 'thanks' => 'top#thanks'
  post "plural_delete_cart_item" => "top#plural_delete_cart_item"

  post "cart" => "top#add"
  get "cart" => "top#add"
  get 'confirm' => 'top#confirm'
  post 'confirm' => 'top#confirm'
  get 'pay' => 'top#pay'
  post 'pay' => 'top#pay'

  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions',
   :registrations => 'users/registrations'
  }
  

  namespace :admin do
    root to: "top#index"
    
    resource :session, only: [:create, :destroy]
    
    get "items/change_subcategories"
    get "items/subcategory"
    get "items/units"
    post "items/plural_destroy"
    post "categories/plural_destroy"
    post "subcategories/plural_destroy"
    post "denominations/plural_destroy"
    post "conditions/plural_destroy"
    post "fabrics/plural_destroy"
    post "units/plural_destroy"
    post "item_types/plural_destroy"
    post "new_arrivals/plural_destroy"
    post "recommendations/plural_destroy"
    post "authorities/plural_destroy"
    post "administrators/plural_destroy"
    post "statuses/plural_destroy"
    post "colors/plural_destroy"
    post "purchases/plural_destroy"
    
    
    resources :items do
      collection {get "search"}
    end
    
    resources :categories do
      collection {get "search"}
    end
    
    resources :subcategories do
      collection {get "search"}
    end
    
    resources :denominations do
      collection {get "search"}
    end
    
    resources :conditions do
      collection {get "search"}
    end
    
    resources :fabrics do
      collection {get "search"}
    end
    
    resources :units do
      collection {get "search"}
    end
    
    resources :item_types do
      collection {get "search"}
    end
    
    resources :new_arrivals do
      collection {get "search"}
    end
    
    resources :purchases do
      collection {get "search"}
    end
    
    resources :recommendations do
      collection {get "search"}
    end
    
    resources :statuses do
      collection {get "search"}
    end
    
    resources :colors do
      collection {get "search"}
    end
    
    resources :authorities do
      collection {get "search"}
    end
    
    resources :administrators do
      collection {get "search"}
    end
    
    get "get_image1" => "items#get_image1"
    get "get_image2" => "items#get_image2"
    get "get_image3" => "items#get_image3"
    get "get_image4" => "items#get_image4"
    get "get_image" => "recommendations#get_image"
    
  end

  

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  scope :active, lambda { where(:deleted => false) }
  has_secure_password
    
  validates :password, presence: { on: :create },
    confirmation: { allow_blank: true }
  
  def password=(val)
    if val.present?
      self.password_digest = BCrypt::Password.create(val)
    end
    @password = val
  end 
  

   
  class << self
    def authenticate(userid, password)
      administrator = find_by_userid(userid)
      if administrator && administrator.password_digest.present? &&
        BCrypt::Password.new(administrator.password_digest) == password
        administrator
      else
        nil
      end
    end
    
    
    def search(query)
      rel=order("id")
      if query.present?
        rel=rel.where("name Like ?", "%#{query}%")
      end
      rel
    end
  end
end

app/controllers/admin/administrators_controller.rb
# coding: utf-8

class Admin::AdministratorsController < ApplicationController
  def index
    @administrators=Administrator.active.all.paginate(:page => params[:page], :per_page => 10)
  end
  
  
  def show
    @administrator=Administrator.active.find(params[:id])
  end
  
  def new
    @administrator=Administrator.new
  end
  
  def edit
    @administrator=Administrator.active.find(params[:id])
  end
  
  def create
    @administrator=Administrator.new(administrator_params)
    if @administrator.save
      redirect_to admin_administrator_path(@administrator), notice: "「"+@administrator.name+"」Registered !"
    else
    render "new"
    end
  end
  
  def update
    @administrator=Administrator.active.find(params[:id])
    @administrator.assign_attributes(administrator_params)
      
    if @administrator.save
      redirect_to admin_administrator_path(@administrator), notice: "「"+@administrator.name+"」Uploaded !"
    else
    render "edit"
    end
  end
  
  def destroy
    @administrator=Administrator.active.find(params[:id])
    @administrator.deleted = true
    if @administrator.save
      redirect_to admin_administrators_path, notice: "「"+@administrator.name+"」Deleted !"
    end
  end
  
  def plural_destroy
    if params[:checked_administrators]
      administrators = params[:checked_administrators].keys
      @administrators=Administrator.active.find(administrators)
      administrator_count=@administrators.size
      @i=0
      @administrators.each do |administrator|
        administrator.deleted = true
        if administrator.save
          @i=@i+1
        end
      end
      if @i=administrator_count
        redirect_to admin_administrators_path, notice: administrator_count.to_s+"件のADMINISTRATORを削除しました"
      end
    else
      redirect_to admin_administrators_path, notice: "削除するADMINISTRATORを選択してください"
    end
  end
  
  def search
    @administrators=Administrator.active.search(params[:q]).paginate(:page => params[:page], :per_page => 10)
    render "index"
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def administrator_params 
    params.require(:administrator).permit(:name, :userid, :password, :password_confirmation, :authority_id, :tel, :email, :create_user, :edit_user, :comment)
  end
  
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/admin/administrators/edit.html.erb
<% @page_title = "contents_name" %>
<% if @current_admin_user && @current_admin_user.authority_id==1 %>
<%= render "shared/admin/info_bar" %>
<%= form_for [:admin, @administrator] do |form| %>
<div class="item_info">
	<p class="top_label">ADMINISTRATOR NAME</p>
	<p class="info"><%= form.text_field :name %></p>
	<p class="label">userid</p>
	<p class="info"><%= form.text_field :userid %></p>
	<p class="label">password</p>
	<p class="info"><%= form.text_field :password %></p>
	<p class="label">password_confirmation</p>
	<p class="info"><%= form.text_field :password_confirmation %></p>
	<p class="label">authority</p>
	<p class="info"><%= form.collection_select :authority_id,Authority.all, :id, :name %></p>
	<p class="label">tel</p>
	<p class="info"><%= form.text_field :tel %></p>
	<p class="label">email</p>
	<p class="info"><%= form.text_field :email %></p>
	<p class="label">comment</p>
	<p class="description"><%= form.text_area :comment %></p>
	
	<%= form.hidden_field :edit_user, :value => @current_admin_user.name %>
	<div class="button">
		<%= form.submit "UPDATE", :class => "update_button" %>
	</div>
</div>
<% end %>
<% elsif @current_admin_user && @current_admin_user.authority_id!=1 %>
<%= render "shared/auth_err" %>
<% else %>
<%= render "shared/login_form" %>
<% end %>

app/views/admin/administrators/index.html.erb
<% @page_title = "administrators" %>
<% if @current_admin_user && @current_admin_user.authority_id==1 %>
<%= render "shared/admin/info_bar" %>
<p class="controll_column_title_top">
	<%= link_to(image_tag("new.png",:size => "40x40", :alt => "new") , new_admin_administrator_path ) %>
</p>
<% if @administrators.present? %>
<div class="table">
<%= form_tag(:action=> 'plural_destroy') do %>
	<table border="1">
		<tr>
			<th class="center" width="55px">
				<p class="column_title">
					<%= image_submit_tag("delete-all-icon.png",:class => "plural_delete", :alt => "plural_delete") %>
					<%= check_box_tag "check_all", :id => "check_all" %>
				</p>
			</th>
			<th class="center" width="40px"><p class="column_title">ID</p></th>
			<th class="center" width="70px">
				<p class="controll_column_title">
					<%= link_to(image_tag("new.png",:size => "40x40", :alt => "new") , new_admin_administrator_path ) %>
				</p>
			</th>
			<th class="center" width="250px"><p class="column_title">NAME</p></th>
			<th class="center" width="250px"><p class="column_title">USERID</p></th>
			<th class="center" width="250px"><p class="column_title">AUTHORITY</p></th>
			<th class="center" width="250px"><p class="column_title">TEL</p></th>
			<th class="center" width="250px"><p class="column_title">EMAIL</p></th>
			<th class="center" width="250px"><p class="column_title">COMMENT</p></th>
			<th class="center" width="100px"><p class="column_title">CREATOR</p></th>
			<th class="center" width="100px"><p class="column_title">EDITOR</p></th>
			<th class="center" width="120px"><p class="column_title">CREATED_AT</p></th>
			<th class="center" width="120px"><p class="column_title">EDITED_AT</p></th>
		</tr>
		<% @administrators.each do|administrator|  %>
		<tr class="<%= cycle("even", "odd") -%>">
			<td class="center"><%= check_box_tag "checked_administrators[#{administrator.id}]", administrator.id, false, :class => "del_check" %></td>
			<td class="center"><%= link_to administrator.id, admin_administrator_path(administrator) , class: "link" %></td>
			<td class="center">
				<%= link_to(image_tag("edit-icon.png",:size => "20x20", :alt => "edit_"+administrator.id.to_s) , [:edit, :admin, administrator], :confirm => "Are You Sure to Delete「"+administrator.name+"」?", :class => "controll_link right" ) %>
				<%= link_to(image_tag("delete-icon.png",:size => "20x20", :alt => "delete_"+administrator.id.to_s) , admin_administrator_path(administrator), method: :delete, :confirm => "Are You Sure to Delete「"+administrator.name+"」?" , :class => "controll_link left") %>
			</td>
			<td class="center"><%= link_to administrator.name, admin_administrator_path(administrator) , class: "link" %></td>
			<td class="center"><%= administrator.userid %></td>
			<% authority=Authority.find(administrator.authority_id) %>
			<td class="center"><%= authority.name %></td>
			<td class="center"><%= administrator.tel %></td>
			<td class="center"><%= administrator.email %></td>
			<td><%= simple_format(administrator.comment) %></td>
			<td class="center"><%= administrator.create_user %></td>
			<td class="center"><%= administrator.edit_user %></td>
			<td class="center"><%= administrator.created_at.try(:strftime,"%Y/%m/%d") %></td>
			<td class="center"><%= administrator.updated_at.try(:strftime,"%Y/%m/%d") %></td>
		</tr>
		<% end %>
	</table>
<% end %>
</div>
<% else %>
	<p class="no_administrator">No administrator Registered !</p>
<% end %>

<% elsif @current_admin_user && @current_admin_user.authority_id!=1 %>
<%= render "shared/auth_err" %>
<% else %>
<%= render "shared/login_form" %>
<% end %>

app/views/admin/administrators/new.html.erb
<% @page_title = "contents_name" %>
<% if @current_admin_user && @current_admin_user.authority_id==1 %>
<%= render "shared/admin/info_bar" %>
<%= form_for [:admin, @administrator] do |form| %>
<div class="item_info">
	<p class="top_label">ADMINISTRATOR NAME</p>
	<p class="info"><%= form.text_field :name %></p>
	<p class="label">userid</p>
	<p class="info"><%= form.text_field :userid %></p>
	<p class="label">password</p>
	<p class="info"><%= form.text_field :password %></p>
	<p class="label">password_confirmation</p>
	<p class="info"><%= form.text_field :password_confirmation %></p>
	<p class="label">authority</p>
	<p class="info"><%= form.collection_select :authority_id,Authority.all, :id, :name %></p>
	<p class="label">tel</p>
	<p class="info"><%= form.text_field :tel %></p>
	<p class="label">email</p>
	<p class="info"><%= form.text_field :email %></p>
	<p class="label">comment</p>
	<p class="description"><%= form.text_area :comment %></p>
	
	<%= form.hidden_field :create_user, :value => @current_admin_user.name %>
	<%= form.hidden_field :edit_user, :value => @current_admin_user.name %>
	<div class="button">
	<%= form.submit "CREATE", :class => "create_button" %>
</div>
</div>

<% end %>
<% elsif @current_admin_user && @current_admin_user.authority_id!=1 %>
<%= render "shared/auth_err" %>
<% else %>
<%= render "shared/login_form" %>
<% end %>

app/views/admin/administrators/show.html.erb
<% @page_title = "contents_name" %>
<% if @current_admin_user && @current_admin_user.authority_id==1 %>
<%= render "shared/admin/info_bar" %>
<div class="controll">
	<%= link_to(image_tag("edit-icon.png",:size => "30x30", :alt => "edit_"+@administrator.id.to_s) , [:edit, :admin, @administrator] ) %>
	<%= link_to(image_tag("delete-icon.png",:size => "30x30", :alt => "delete_"+@administrator.id.to_s) , admin_administrator_path(@administrator), method: :delete, confirm: "Are You Sure to Delete「"+@administrator.name+"」?" ) %>
</div>
<div class="item_info">
	<h1> <%= @administrator.name %> </h1>
	<p class="label">userid</p>
	<p class="info"><%= @administrator.userid %></p>
	<p class="label">authority</p>
	<% authority=Authority.find(@administrator.authority_id) %>
	<p class="info"><%= authority.name %></p>
	<p class="label">tel</p>
	<p class="info"><%= @administrator.tel %></p>
	<p class="label">email</p>
	<p class="info"><%= @administrator.email %></p>
</div>
<div class="item_info">
		<p class="label">creator</p>
	<p class="info"><%= @administrator.create_user %></p>
	<p class="label">editor</p>
	<p class="info"><%= @administrator.edit_user %></p>
	<p class="label">created at</p>
	<p class="info"><%= @administrator.created_at.try(:strftime,"%Y/%m/%d %H:%M") %></p>
	<p class="label">edited at</p>
	<p class="info"><%= @administrator.updated_at.try(:strftime,"%Y/%m/%d %H:%M") %></p>
	<p class="label">comment</p>
	<p class="info"><%= simple_format(@administrator.comment) %></p>
</div>
<% elsif @current_admin_user && @current_admin_user.authority_id!=1 %>
<%= render "shared/auth_err" %>
<% else %>
<%= render "shared/login_form" %>
<% end %>