config/routes.rb
Rails.application.routes.draw do
  root to: "top#index"
  get "about_us" => "top#about_us"
  get "show_item" => "top#show_item"
  get "categorized" => "top#categorized"  
  get "get_image1" => "top#get_image1"
  get "get_image2" => "top#get_image2"
  get "get_image3" => "top#get_image3"
  get "get_image4" => "top#get_image4"
  get "new_arrivals" => "top#new_arrivals"
  get "recommend" => "top#recommend"
  get "blog" => "top#blog"
  get "contact" => "top#contact"
  get "search" => "top#search"
  get "checkout" => "top#checkout"
  get "delete_cart_item" => "top#delete_cart_item"
  get 'thanks' => 'top#thanks'
  post "plural_delete_cart_item" => "top#plural_delete_cart_item"

  post "cart" => "top#add"
  get "cart" => "top#add"
  get 'confirm' => 'top#confirm'
  post 'confirm' => 'top#confirm'
  get 'pay' => 'top#pay'
  post 'pay' => 'top#pay'

  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions',
   :registrations => 'users/registrations'
  }
  

  namespace :admin do
    root to: "top#index"
    
    resource :session, only: [:create, :destroy]
    
    get "items/change_subcategories"
    get "items/subcategory"
    get "items/units"
    post "items/plural_destroy"
    post "categories/plural_destroy"
    post "subcategories/plural_destroy"
    post "denominations/plural_destroy"
    post "conditions/plural_destroy"
    post "fabrics/plural_destroy"
    post "units/plural_destroy"
    post "item_types/plural_destroy"
    post "new_arrivals/plural_destroy"
    post "recommendations/plural_destroy"
    post "authorities/plural_destroy"
    post "administrators/plural_destroy"
    post "statuses/plural_destroy"
    post "colors/plural_destroy"
    post "purchases/plural_destroy"
    
    
    resources :items do
      collection {get "search"}
    end
    
    resources :categories do
      collection {get "search"}
    end
    
    resources :subcategories do
      collection {get "search"}
    end
    
    resources :denominations do
      collection {get "search"}
    end
    
    resources :conditions do
      collection {get "search"}
    end
    
    resources :fabrics do
      collection {get "search"}
    end
    
    resources :units do
      collection {get "search"}
    end
    
    resources :item_types do
      collection {get "search"}
    end
    
    resources :new_arrivals do
      collection {get "search"}
    end
    
    resources :purchases do
      collection {get "search"}
    end
    
    resources :recommendations do
      collection {get "search"}
    end
    
    resources :statuses do
      collection {get "search"}
    end
    
    resources :colors do
      collection {get "search"}
    end
    
    resources :authorities do
      collection {get "search"}
    end
    
    resources :administrators do
      collection {get "search"}
    end
    
    get "get_image1" => "items#get_image1"
    get "get_image2" => "items#get_image2"
    get "get_image3" => "items#get_image3"
    get "get_image4" => "items#get_image4"
    get "get_image" => "recommendations#get_image"
    
  end

  

end

app/controllers/admin/item_types_controller.rb
# coding: utf-8

class Admin::ItemTypesController < ApplicationController
  def index
    @item_types=ItemType.active.all.paginate(:page => params[:page], :per_page => 10)
  end
  
  
  def show
    @item_type=ItemType.active.find(params[:id])
  end
  
  def new
    @item_type=ItemType.new
  end
  
  def edit
    @item_type=ItemType.active.find(params[:id])
  end
  
  def create
    @item_type=ItemType.new(item_type_params)
    unit_id_list=params[:item_type][:unit_id_list]
    unit_id_list.delete("")
    @item_type.unit_id_list=unit_id_list
    if @item_type.save
      redirect_to admin_item_type_path(@item_type), notice: "「"+@item_type.name+"」Registered !"
    else
    render "new"
    end
  end
  
  def update
    @item_type=ItemType.active.find(params[:id])
    @item_type.assign_attributes(item_type_params)
    unit_id_list=params[:item_type][:unit_id_list]
    unit_id_list.delete("")
    @item_type.unit_id_list=unit_id_list
    if @item_type.save
      redirect_to admin_item_type_path(@item_type), notice: "「"+@item_type.name+"」Uploaded !"
    else
    render "edit"
    end
  end
  
  def destroy
    @item_type=ItemType.active.find(params[:id])
    @item_type.deleted = true
    if @item_type.save
      redirect_to admin_item_types_path, notice: "「"+@item_type.name+"」Deleted !"
    end
  end
  
  def plural_destroy
    if params[:checked_item_types]
      item_types = params[:checked_item_types].keys
      @item_types=ItemType.active.find(item_types)
      item_type_count=@item_types.size
      @i=0
      @item_types.each do |item_type|
        item_type.deleted = true
        if item_type.save
          @i=@i+1
        end
      end
      if @i=item_type_count
        redirect_to admin_item_types_path, notice: item_type_count.to_s+"件のITEM TYPEを削除しました"
      end
    else
      redirect_to admin_item_types_path, notice: "削除するITEM TYPEを選択してください"
    end
  end
  
  def search
    @item_types=ItemType.active.search(params[:q]).paginate(:page => params[:page], :per_page => 10)
    render "index"
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def item_type_params 
    params.require(:item_type).permit(:name, :unit_id_list, :create_user, :edit_user, :comment)
   end

end

app/helpers/item_types_helper.rb
module ItemTypesHelper
end

app/views/admin/item_types/edit.html.erb
<% @page_title = "contents_name" %>
<% if @current_admin_user && (@current_admin_user.authority_id==1||@current_admin_user.authority_id==2) %>
<%= render "shared/admin/info_bar" %>
<%= form_for [:admin, @item_type] do |form| %>
<div class="item_info">
	<p class="top_label">ITEM TYPE NAME</p>
	<p class="info"><%= form.text_field :name %></p>
	<%= form.hidden_field :edit_user, :value => @current_admin_user.name %>
	<p class="label">units</p>
	<p class="list"><%= form.collection_select( :unit_id_list, Unit.active.all, :id, :name_and_unit,{}, {:multiple => true, :size => Unit.active.all.size}) %></p>
	<p class="label">comment</p>
	<p class="description"><%= form.text_area :comment %></p>
	<div class="button">
		<%= form.submit "UPDATE", :class => "update_button" %>
	</div>
</div>
<% end %>
<% elsif @current_admin_user && @current_admin_user.authority_id!=1 && @current_admin_user.authority_id!=2 %>
<%= render "shared/auth_err" %>
<% else %>
<%= render "shared/login_form" %>
<% end %>

app/views/admin/item_types/index.html.erb
<% @page_title = "item types" %>
<% if @current_admin_user %>
<%= render "shared/admin/info_bar" %>
<% if @current_admin_user.authority_id==1||@current_admin_user.authority_id==2 %>
<p class="controll_column_title_top">
	<%= link_to(image_tag("new.png",:size => "40x40", :alt => "new") , new_admin_item_type_path ) %>
</p>
<% else %>
<p class="controll_column_title_top"></p>
<% end %>
<% if @item_types.present? %>
<div class="table">
<%= form_tag(:action=> 'plural_destroy') do %>
	<table border="1">
		<tr>
			<% if @current_admin_user.authority_id==1||@current_admin_user.authority_id==2 %>
			<th class="center" width="55px">
				<p class="column_title">
					<%= image_submit_tag("delete-all-icon.png",:class => "plural_delete", :alt => "plural_delete") %>
					<%= check_box_tag "check_all", :id => "check_all" %>
				</p>
			</th>
			<% end %>
			<th class="center" width="40px"><p class="column_title">ID</p></th>
			<% if @current_admin_user.authority_id==1||@current_admin_user.authority_id==2 %>
			<th class="center" width="70px">
				<p class="controll_column_title">
					<%= link_to(image_tag("new.png",:size => "40x40", :alt => "new") , new_admin_item_type_path ) %>
				</p>
			</th>
			<% end %>
			<th class="center" width="250px"><p class="column_title">NAME</p></th>
			<th class="center" width="100px"><p class="column_title">UNITS</p></th>
			<th class="center" width="250px"><p class="column_title">COMMENT</p></th>
			<th class="center" width="100px"><p class="column_title">CREATOR</p></th>
			<th class="center" width="100px"><p class="column_title">EDITOR</p></th>
			<th class="center" width="120px"><p class="column_title">CREATED_AT</p></th>
			<th class="center" width="120px"><p class="column_title">EDITED_AT</p></th>
		</tr>
		<% @item_types.each do|item_type|  %>
		<tr class="<%= cycle("even", "odd") -%>">
			<% if @current_admin_user.authority_id==1||@current_admin_user.authority_id==2 %>
			<td class="center"><%= check_box_tag "checked_item_types[#{item_type.id}]", item_type.id, false, :class => "del_check" %></td>
			<% end %>
			<td class="center"><%= link_to item_type.id, admin_item_type_path(item_type) , class: "link" %></td>
			<% if @current_admin_user.authority_id==1||@current_admin_user.authority_id==2 %>
			<td class="center">
				<%= link_to(image_tag("edit-icon.png",:size => "20x20", :alt => "edit_"+item_type.id.to_s) , [:edit, :admin, item_type], :confirm => "Are You Sure to Delete「"+item_type.name+"」?", :class => "controll_link right" ) %>
				<%= link_to(image_tag("delete-icon.png",:size => "20x20", :alt => "delete_"+item_type.id.to_s) , admin_item_type_path(item_type), method: :delete, :confirm => "Are You Sure to Delete「"+item_type.name+"」?" , :class => "controll_link left") %>
			</td>
			<% end %>
			<td class="center"><%= link_to item_type.name, admin_item_type_path(item_type) , class: "link" %></td>
			<td class="center">
			<% if item_type.unit_id_list %>
				<% item_type.unit_id_list.each do |unit| %>
				<% @unit=Unit.find(unit.to_i) %>
				<%= @unit.name %>:
				<%= @unit.unit %>
				<br />
				<% end %>
			<% end %>
			</td>
			<td><%= simple_format(item_type.comment) %></td>
			<td class="center"><%= item_type.create_user %></td>
			<td class="center"><%= item_type.edit_user %></td>
			<td class="center"><%= item_type.created_at.try(:strftime,"%Y/%m/%d") %></td>
			<td class="center"><%= item_type.updated_at.try(:strftime,"%Y/%m/%d") %></td>
		</tr>
		<% end %>
	</table>
<% end %>
</div>
<% else %>
	<p class="no_item_type">No item type Registered !</p>
<% end %>

<% else %>
<%= render "shared/login_form" %>
<% end %>

app/views/admin/item_types/new.html.erb
<% @page_title = "contents_name" %>
<% if @current_admin_user && (@current_admin_user.authority_id==1||@current_admin_user.authority_id==2) %>
<%= render "shared/admin/info_bar" %>
<%= form_for [:admin, @item_type] do |form| %>
<div class="item_info">
	<p class="top_label">ITEM TYPE NAME</p>
	<p class="info"><%= form.text_field :name %></p>
	<%= form.hidden_field :create_user, :value => @current_admin_user.name %>
	<%= form.hidden_field :edit_user, :value => @current_admin_user.name %>
	<p class="label">units</p>
	<p class="list"><%= form.collection_select( :unit_id_list, Unit.active.all, :id, :name_and_unit,{}, {:multiple => true, :size => Unit.active.all.size}) %></p>
	<p class="label">comment</p>
	<p class="description"><%= form.text_area :comment %></p>
	<div class="button">
		<%= form.submit "CREATE", :class => "create_button" %>
	</div>
</div>
<% end %>
<% elsif @current_admin_user && @current_admin_user.authority_id!=1 && @current_admin_user.authority_id!=2 %>
<%= render "shared/auth_err" %>
<% else %>
<%= render "shared/login_form" %>
<% end %>

app/views/admin/item_types/show.html.erb
<% @page_title = "contents_name" %>
<% if @current_admin_user %>
<%= render "shared/admin/info_bar" %>
<% if @current_admin_user.authority_id==1||@current_admin_user.authority_id==2 %>
<div class="controll">
	<%= link_to(image_tag("edit-icon.png",:size => "30x30", :alt => "edit_"+@item_type.id.to_s) , [:edit, :admin, @item_type] ) %>
	<%= link_to(image_tag("delete-icon.png",:size => "30x30", :alt => "delete_"+@item_type.id.to_s) , admin_item_type_path(@item_type), method: :delete, confirm: "Are You Sure to Delete「"+@item_type.name+"」?" ) %>
</div>
<% end %>
<div class="item_info">
	<h1> <%= @item_type.name %> </h1>
	<p class="label">units</p>
	<p class="description">
		<% @item_type.unit_id_list.each do |unit| %>
		<% @unit=Unit.find(unit.to_i) %>
		<%= @unit.name %>:
		<%= @unit.unit %>
		<br />
		<% end %>
	</p>
	<p class="label">creator</p>
	<p class="info"><%= @item_type.create_user %></p>
	<p class="label">editor</p>
	<p class="info"><%= @item_type.edit_user %></p>
	<p class="label">created at</p>
	<p class="info"><%= @item_type.created_at.try(:strftime,"%Y/%m/%d %H:%M") %></p>
	<p class="label">edited at</p>
	<p class="info"><%= @item_type.updated_at.try(:strftime,"%Y/%m/%d %H:%M") %></p>
	<p class="label">comment</p>
	<p class="info"><%= simple_format(@item_type.comment) %></p>
</div>
<% else %>
<%= render "shared/login_form" %>
<% end %>