config/routes.rb
Rails.application.routes.draw do
  root to: "top#index"
  get "about_us" => "top#about_us"
  get "show_item" => "top#show_item"
  get "categorized" => "top#categorized"  
  get "get_image1" => "top#get_image1"
  get "get_image2" => "top#get_image2"
  get "get_image3" => "top#get_image3"
  get "get_image4" => "top#get_image4"
  get "new_arrivals" => "top#new_arrivals"
  get "recommend" => "top#recommend"
  get "blog" => "top#blog"
  get "contact" => "top#contact"
  get "search" => "top#search"
  get "checkout" => "top#checkout"
  get "delete_cart_item" => "top#delete_cart_item"
  get 'thanks' => 'top#thanks'
  post "plural_delete_cart_item" => "top#plural_delete_cart_item"

  post "cart" => "top#add"
  get "cart" => "top#add"
  get 'confirm' => 'top#confirm'
  post 'confirm' => 'top#confirm'
  get 'pay' => 'top#pay'
  post 'pay' => 'top#pay'

  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions',
   :registrations => 'users/registrations'
  }
  

  namespace :admin do
    root to: "top#index"
    
    resource :session, only: [:create, :destroy]
    
    get "items/change_subcategories"
    get "items/subcategory"
    get "items/units"
    post "items/plural_destroy"
    post "categories/plural_destroy"
    post "subcategories/plural_destroy"
    post "denominations/plural_destroy"
    post "conditions/plural_destroy"
    post "fabrics/plural_destroy"
    post "units/plural_destroy"
    post "item_types/plural_destroy"
    post "new_arrivals/plural_destroy"
    post "recommendations/plural_destroy"
    post "authorities/plural_destroy"
    post "administrators/plural_destroy"
    post "statuses/plural_destroy"
    post "colors/plural_destroy"
    post "purchases/plural_destroy"
    
    
    resources :items do
      collection {get "search"}
    end
    
    resources :categories do
      collection {get "search"}
    end
    
    resources :subcategories do
      collection {get "search"}
    end
    
    resources :denominations do
      collection {get "search"}
    end
    
    resources :conditions do
      collection {get "search"}
    end
    
    resources :fabrics do
      collection {get "search"}
    end
    
    resources :units do
      collection {get "search"}
    end
    
    resources :item_types do
      collection {get "search"}
    end
    
    resources :new_arrivals do
      collection {get "search"}
    end
    
    resources :purchases do
      collection {get "search"}
    end
    
    resources :recommendations do
      collection {get "search"}
    end
    
    resources :statuses do
      collection {get "search"}
    end
    
    resources :colors do
      collection {get "search"}
    end
    
    resources :authorities do
      collection {get "search"}
    end
    
    resources :administrators do
      collection {get "search"}
    end
    
    get "get_image1" => "items#get_image1"
    get "get_image2" => "items#get_image2"
    get "get_image3" => "items#get_image3"
    get "get_image4" => "items#get_image4"
    get "get_image" => "recommendations#get_image"
    
  end

  

end

app/views/shared/_auth_err.html.erb
<p>こちらのページへのアクセス権限がありません。</p>
<%= link_to '戻る', :back %> 

app/views/shared/_footer.html.erb
<footer>
	<%= link_to_unless_current "HOME", root_path %>
	<%= link_to "ABOUT US", about_us_path, class: :"other_links" %>
	<%= link_to "PRIVACY NOTICE", about_us_path, class: :"other_links" %>
	<p class="CopyRight">ALL RIGHTS RESERVED (C) 2015 VINTAGE VINTAGE</p>
</footer>

app/views/shared/_header.html.erb
<header>
	<ul class = "top_list">
		<li>
			<%= link_to root_path do %>
				<p class = "home">Home</p>
				<%= image_tag("home.png",:size => "15x15", :alt => "home") %>
			<% end %>
		</li>
		<li>
		    <% if user_signed_in? %> 
		      <ul class="user_info_lists">
		      	<li class = "first_list">
		      		<%= link_to edit_user_registration_path do %>
						<p>Account</p>
						<%= image_tag("menu.png",:size => "15x15", :alt => "account") %>
					<% end %>
		      	</li>
		      	<li class = "other_row">
		      		<%= link_to edit_user_registration_path do %>
						<p>Preference</p>
						<%= image_tag("settings.png",:size => "15x15", :alt => "account settings") %>
					<% end %>
		      	</li>
		      	<li class = "other_row">
			      	<%= link_to destroy_user_session_path, method: :delete do %>
						<p>Logout</p>
						<%= image_tag("logout.png",:size => "15x15", :alt => "logout") %>
					<% end %>
				</li>
		      </ul>
		    <% else %>
      		<%= link_to new_user_session_path do %>
				<p class = "login">Login</p>
				<%= image_tag("sign_in.png",:size => "15x15", :alt => "sign in") %>
			<% end %>
		    <% end %>
		</li>
		<li>
			<% if !user_signed_in? %>
	      		<%= link_to new_user_registration_path do %>
					<p class = "sign_up">Sign up</p>
					<%= image_tag("sign_up.png",:size => "15x15", :alt => "sign up") %>
				<% end %>
			<% end %>
		</li>
	</ul>
	<div class="Logo">
		<a href="<%= root_path %>">
		<h1>vintage vintage</h1>
		<p>try on the someone's story</p>
		</a>
	</div>
	<div class="R_header">
		<div class="cart_area">
			<% if session[:cart] %>
	  		<%= link_to cart_path do %>
				<%= image_tag("cart.png",:size => "15x15", :alt => "cart", :class => "cart_logo") %>
				<% if session[:cart].items.count == 0 || session[:cart].items.count == 1 %>
					<% s = "" %>
				<% else %>
					<% s = "s" %>
				<% end %>
				<p class = "cart"><%= session[:cart].items.count.to_s+" Item"+s %></p>
			<% end %>
			<% end %>
		</div>
		<%= form_tag :search, method: :get do %>
			<p class="serch_text"><%= text_field_tag "q", params[:q] %></p>
			<%= image_submit_tag("search.png",{:size => "15x15", :alt => "search", :class => "search_button"}) %>
		<% end %>
	</div>
</header>

app/views/shared/_login_form.html.erb
<div class="login_page">
	<%= image_tag("Recommend.jpg", :size => "980x300", :alt => "Recommended", class: :"title-img") %>
	<div class="login_form">
		<h2>LOGIN</h2>
		<% if flash.alert %>
		<p class="alert"><%= flash.alert %></p>
		<% end %>
		
		<%= form_tag :admin_session do %>
		<table>
			<tr>
				<td><%= text_field_tag "userid", nil, :placeholder => "UserID", :class => "login_field" %></td>
			</tr>
			<tr>
				<td><%= password_field_tag "password", nil, :placeholder => "Password", :class => "login_field" %></td>
			</tr>
			<tr>
				<td class="login_button_layout" colspan="2"><%= submit_tag "LOGIN" , :class => "login_button" %></td>
			</tr>
		</table>
		<%= hidden_field_tag "from", request.path %>
		<% end %>
	</div>
</div>

app/views/shared/_side_menu.html.erb
<div class="side_menu">
	<h2>Categories</h2>
	<ul>
		<li><%= link_to_unless_current "HOME", root_path %></li>
	<% @categories.zip(@subcategories_list).each do |category,subcategories| %>
		<li><%= link_to_unless_current category.name, categorized_path(category:category, category_name: category.name)  %></li>
		<% subcategories.each do |subcategory| %>
		<li class="subcategory"><%= link_to_unless_current subcategory.name, categorized_path(category: category, subcategory: subcategory, category_name: category.name, subcategory_name: subcategory.name)  %></li>
		<% end %>
	<% end %>
	</ul>
</div>