config/routes.rb
Rails.application.routes.draw do
  root to: "top#index"
  get "about_us" => "top#about_us"
  get "show_item" => "top#show_item"
  get "categorized" => "top#categorized"  
  get "get_image1" => "top#get_image1"
  get "get_image2" => "top#get_image2"
  get "get_image3" => "top#get_image3"
  get "get_image4" => "top#get_image4"
  get "new_arrivals" => "top#new_arrivals"
  get "recommend" => "top#recommend"
  get "blog" => "top#blog"
  get "contact" => "top#contact"
  get "search" => "top#search"
  get "checkout" => "top#checkout"
  get "delete_cart_item" => "top#delete_cart_item"
  get 'thanks' => 'top#thanks'
  post "plural_delete_cart_item" => "top#plural_delete_cart_item"

  post "cart" => "top#add"
  get "cart" => "top#add"
  get 'confirm' => 'top#confirm'
  post 'confirm' => 'top#confirm'
  get 'pay' => 'top#pay'
  post 'pay' => 'top#pay'

  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions',
   :registrations => 'users/registrations'
  }
  

  namespace :admin do
    root to: "top#index"
    
    resource :session, only: [:create, :destroy]
    
    get "items/change_subcategories"
    get "items/subcategory"
    get "items/units"
    post "items/plural_destroy"
    post "categories/plural_destroy"
    post "subcategories/plural_destroy"
    post "denominations/plural_destroy"
    post "conditions/plural_destroy"
    post "fabrics/plural_destroy"
    post "units/plural_destroy"
    post "item_types/plural_destroy"
    post "new_arrivals/plural_destroy"
    post "recommendations/plural_destroy"
    post "authorities/plural_destroy"
    post "administrators/plural_destroy"
    post "statuses/plural_destroy"
    post "colors/plural_destroy"
    post "purchases/plural_destroy"
    
    
    resources :items do
      collection {get "search"}
    end
    
    resources :categories do
      collection {get "search"}
    end
    
    resources :subcategories do
      collection {get "search"}
    end
    
    resources :denominations do
      collection {get "search"}
    end
    
    resources :conditions do
      collection {get "search"}
    end
    
    resources :fabrics do
      collection {get "search"}
    end
    
    resources :units do
      collection {get "search"}
    end
    
    resources :item_types do
      collection {get "search"}
    end
    
    resources :new_arrivals do
      collection {get "search"}
    end
    
    resources :purchases do
      collection {get "search"}
    end
    
    resources :recommendations do
      collection {get "search"}
    end
    
    resources :statuses do
      collection {get "search"}
    end
    
    resources :colors do
      collection {get "search"}
    end
    
    resources :authorities do
      collection {get "search"}
    end
    
    resources :administrators do
      collection {get "search"}
    end
    
    get "get_image1" => "items#get_image1"
    get "get_image2" => "items#get_image2"
    get "get_image3" => "items#get_image3"
    get "get_image4" => "items#get_image4"
    get "get_image" => "recommendations#get_image"
    
  end

  

end

app/models/authority.rb
class Authority < ActiveRecord::Base
  scope :active, lambda { where(:deleted => false) }
    
  class << self
    def search(query)
      rel=order("id")
      if query.present?
        rel=rel.where("name Like ?", "%#{query}%")
      end
      rel
    end
  end
end

app/controllers/admin/authorities_controller.rb
# coding: utf-8

class Admin::AuthoritiesController < ApplicationController
  def index
    @authorities=Authority.active.all.paginate(:page => params[:page], :per_page => 10)
  end
  
  
  def show
    @authority=Authority.active.find(params[:id])
  end
  
  def new
    @authority=Authority.new
  end
  
  def edit
    @authority=Authority.active.find(params[:id])
  end
  
  def create
    @authority=Authority.new(authority_params)
    if @authority.save
      redirect_to admin_authority_path(@authority), notice: "「"+@authority.name+"」Registered !"
    else
    render "new"
    end
  end
  
  def update
    @authority=Authority.active.find(params[:id])
    @authority.assign_attributes(authority_params)
      
    if @authority.save
      redirect_to admin_authority_path(@authority), notice: "「"+@authority.name+"」Uploaded !"
    else
    render "edit"
    end
  end
  
  def destroy
    @authority=Authority.active.find(params[:id])
    @authority.deleted = true
    if @authority.save
      redirect_to admin_authorities_path, notice: "「"+@authority.name+"」Deleted !"
    end
  end
  
  def plural_destroy
    if params[:checked_authorities]
      authorities = params[:checked_authorities].keys
      @authorities=Authority.active.find(authorities)
      authority_count=@authorities.size
      @i=0
      @authorities.each do |authority|
        authority.deleted = true
        if authority.save
          @i=@i+1
        end
      end
      if @i=authority_count
        redirect_to admin_authorities_path, notice: authority_count.to_s+"件のAUTHORITYを削除しました"
      end
    else
      redirect_to admin_authorities_path, notice: "削除するAUTHORITYを選択してください"
    end
  end
  
  def search
    @authorities=Authority.active.search(params[:q]).paginate(:page => params[:page], :per_page => 10)
    render "index"
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def authority_params 
    params.require(:authority).permit(:name, :authority, :comment)
  end
  
end

app/helpers/authorities_helper.rb
module AuthoritiesHelper
end

app/views/admin/authorities/edit.html.erb
<% @page_title = "contents_name" %>
<% if @current_admin_user && @current_admin_user.authority_id==1 %>
<%= render "shared/admin/info_bar" %>
<%= form_for [:admin, @authority] do |form| %>
<div class="item_info">
	<p class="top_label">AUTHORITY NAME</p>
	<p class="info"><%= form.text_field :name %></p>
	<p class="label">authority</p>
	<p class="description"><%= form.text_area :authority %></p>
	<p class="label">comment</p>
	<p class="description"><%= form.text_area :comment %></p>
	<div class="button">
		<%= form.submit "UPDATE", :class => "update_button" %>
	</div>
</div>
<% end %>
<% elsif @current_admin_user && @current_admin_user.authority_id!=1 %>
<%= render "shared/auth_err" %>
<% else %>
<%= render "shared/login_form" %>
<% end %>

app/views/admin/authorities/index.html.erb
<% @page_title = "authoritys" %>
<% if @current_admin_user && @current_admin_user.authority_id==1 %>
<%= render "shared/admin/info_bar" %>
<p class="controll_column_title_top">
	<%= link_to(image_tag("new.png",:size => "40x40", :alt => "new") , new_admin_authority_path ) %>
</p>
<% if @authorities.present? %>
<div class="table">
<%= form_tag(:action=> 'plural_destroy') do %>
	<table border="1">
		<tr>
			<th class="center" width="55px">
				<p class="column_title">
					<%= image_submit_tag("delete-all-icon.png",:class => "plural_delete", :alt => "plural_delete") %>
					<%= check_box_tag "check_all", :id => "check_all" %>
				</p>
			</th>
			<th class="center" width="40px"><p class="column_title">ID</p></th>
			<th class="center" width="70px">
				<p class="controll_column_title">
					<%= link_to(image_tag("new.png",:size => "40x40", :alt => "new") , new_admin_authority_path ) %>
				</p>
			</th>
			<th class="center" width="250px"><p class="column_title">NAME</p></th>
			<th class="center" width="250px"><p class="column_title">AUTHORITY</p></th>
			<th class="center" width="250px"><p class="column_title">COMMENT</p></th>
			<th class="center" width="120px"><p class="column_title">CREATED_AT</p></th>
			<th class="center" width="120px"><p class="column_title">EDITED_AT</p></th>
		</tr>
		<% @authorities.each do|authority|  %>
		<tr class="<%= cycle("even", "odd") -%>">
			<td class="center"><%= check_box_tag "checked_authorities[#{authority.id}]", authority.id, false, :class => "del_check" %></td>
			<td class="center"><%= link_to authority.id, admin_authority_path(authority) , class: "link" %></td>
			<td class="center">
				<%= link_to(image_tag("edit-icon.png",:size => "20x20", :alt => "edit_"+authority.id.to_s) , [:edit, :admin, authority], :confirm => "Are You Sure to Delete「"+authority.name+"」?", :class => "controll_link right" ) %>
				<%= link_to(image_tag("delete-icon.png",:size => "20x20", :alt => "delete_"+authority.id.to_s) , admin_authority_path(authority), method: :delete, :confirm => "Are You Sure to Delete「"+authority.name+"」?" , :class => "controll_link left") %>
			</td>
			<td class="center"><%= link_to authority.name, admin_authority_path(authority) , class: "link" %></td>
			<td><%= authority.authority %></td>
			<td><%= simple_format(authority.comment) %></td>
			<td class="center"><%= authority.created_at.try(:strftime,"%Y/%m/%d") %></td>
			<td class="center"><%= authority.updated_at.try(:strftime,"%Y/%m/%d") %></td>
		</tr>
		<% end %>
	</table>
<% end %>
</div>
<% else %>
	<p class="no_authority">No authority Registered !</p>
<% end %>

<% elsif @current_admin_user && @current_admin_user.authority_id!=1 %>
<%= render "shared/auth_err" %>
<% else %>
<%= render "shared/login_form" %>
<% end %>

app/views/admin/authorities/new.html.erb
<% @page_title = "contents_name" %>
<% if @current_admin_user && @current_admin_user.authority_id==1 %>
<%= render "shared/admin/info_bar" %>
<%= form_for [:admin, @authority] do |form| %>
<div class="item_info">
	<p class="top_label">AUTHORITY NAME</p>
	<p class="info"><%= form.text_field :name %></p>
	<p class="label">authority</p>
	<p class="description"><%= form.text_area :authority %></p>
	<p class="label">comment</p>
	<p class="description"><%= form.text_area :comment %></p>
	<div class="button">
		<%= form.submit "CREATE", :class => "create_button" %>
	</div>
</div>
<% end %>
<% elsif @current_admin_user && @current_admin_user.authority_id!=1 %>
<%= render "shared/auth_err" %>
<% else %>
<%= render "shared/login_form" %>
<% end %>

app/views/admin/authorities/show.html.erb
<% @page_title = "contents_name" %>
<% if @current_admin_user && @current_admin_user.authority_id==1 %>
<%= render "shared/admin/info_bar" %>
<div class="controll">
	<%= link_to(image_tag("edit-icon.png",:size => "30x30", :alt => "edit_"+@authority.id.to_s) , [:edit, :admin, @authority] ) %>
	<%= link_to(image_tag("delete-icon.png",:size => "30x30", :alt => "delete_"+@authority.id.to_s) , admin_authority_path(@authority), method: :delete, confirm: "Are You Sure to Delete「"+@authority.name+"」?" ) %>
</div>
<div class="item_info">
	<h1> <%= @authority.name %> </h1>
	<p class="label">authority</p>
	<p class="description"><%= @authority.authority %></p>
	<p class="label">created at</p>
	<p class="info"><%= @authority.created_at.try(:strftime,"%Y/%m/%d %H:%M") %></p>
	<p class="label">edited at</p>
	<p class="info"><%= @authority.updated_at.try(:strftime,"%Y/%m/%d %H:%M") %></p>
	<p class="label">comment</p>
	<p class="info"><%= simple_format(@authority.comment) %></p>
</div>
<% elsif @current_admin_user && @current_admin_user.authority_id!=1 %>
<%= render "shared/auth_err" %>
<% else %>
<%= render "shared/login_form" %>
<% end %>